let me=null,jobsData=[],apps=[],interviews=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=id=>document.getElementById(id);

document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.add('hide'));el(b.dataset.tab)?.classList.remove('hide');}));

async function getStudentContext(){
  const {data:{user},error:ue}=await sb.auth.getUser();
  if(ue||!user) return null;
  if(me?.id===user.id) return me;
  const {data:p,error:pe}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();
  if(pe) throw pe;
  if(!p) throw new Error('Student profile was not found for this login. Please contact the TPO.');
  if(p.role!== 'student') throw new Error('This account is not a student account.');
  me=p; window.me=me;
  return me;
}

async function init(){
  try{
    const p=await getStudentContext();
    if(!p) return location.replace('login.html?role=student');
    if(p.is_active===false){alert('Your student account is inactive. Contact the TPO.');await sb.auth.signOut();return location.replace('index.html');}
    fillProfile();initProfilePicturePreview();await Promise.all([loadJobs(),loadApps(),loadInterviews(),loadNotifications(),loadPractice(),loadHistory(),loadPlacementStats()]);updateHome();
  }catch(e){
    console.error(e);
    const msg=el('profilePictureMsg');
    if(msg){msg.textContent=` ${e?.message||e}`;msg.className='error';}
  }
}
function fillProfile(){el('name').textContent=me.full_name||'Student';el('pName').value=me.full_name||'';el('pEmail').value=me.email||'';el('pPhone').value=me.phone||'';el('pDept').value=me.department||'';el('pQualification').value=me.qualification||'';el('pRoll').value=me.roll_no||'';el('pCgpa').value=me.cgpa??'';el('pSkills').value=(me.skills||[]).join(', ');el('pCerts').value=(me.certifications||[]).join(', ');el('pProjects').value=(me.projects||[]).join('\n');el('pLocation').value=me.preferred_location||'';el('pExperience').value=me.experience||'';const img=el('studentAvatar'),ph=el('studentAvatarPlaceholder'),head=el('headerStudentAvatar');if(head){head.src=me.profile_picture_url||'';head.classList.toggle('visible',!!me.profile_picture_url);}if(img&&ph){if(me.profile_picture_url){img.src=me.profile_picture_url;img.classList.add('visible');ph.classList.add('hide');}else{img.src='';img.classList.remove('visible');ph.classList.remove('hide');ph.textContent=(me.full_name||'Student').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();}}renderCV();}
async function saveProfile(){const patch={full_name:el('pName').value.trim(),email:el('pEmail').value.trim(),phone:el('pPhone').value.trim(),department:el('pDept').value.trim(),qualification:el('pQualification').value.trim(),roll_no:el('pRoll').value.trim(),cgpa:el('pCgpa').value?Number(el('pCgpa').value):null,skills:el('pSkills').value.split(',').map(x=>x.trim()).filter(Boolean),certifications:el('pCerts').value.split(',').map(x=>x.trim()).filter(Boolean),projects:el('pProjects').value.split('\n').map(x=>x.trim()).filter(Boolean),preferred_location:el('pLocation').value.trim(),experience:el('pExperience').value.trim()};const {data,error}=await sb.from('profiles').update(patch).eq('id',me.id).select('*').single();const m=el('profileMsg');m.textContent=error?` ${error.message}`:' ✓ Profile saved';m.className=error?'error':'success';if(!error){me=data;window.me=me;fillProfile();await loadJobs();updateHome();}}


async function withTimeout(promise, ms=15000, label='Operation') {
  return await Promise.race([promise, new Promise((_, reject)=>setTimeout(()=>reject(new Error(`${label} timed out. Check your internet connection and Supabase Storage.`)), ms))]);
}
async function uploadProfilePicture(){
  const file=el('profilePictureFile')?.files?.[0];
  const msg=el('profilePictureMsg');
  if(!file){if(msg){msg.textContent=' Choose a JPG, PNG or WEBP image first.';msg.className='error';}return;}
  if(file.size>3*1024*1024){if(msg){msg.textContent=' Please keep the profile picture under 3 MB.';msg.className='error';}return;}
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)){if(msg){msg.textContent=' Only JPG, PNG and WEBP images are supported.';msg.className='error';}return;}
  if(msg){msg.textContent=' Preparing upload…';msg.className='muted';}
  try {
    const profile=await withTimeout(getStudentContext(),10000,'Student profile lookup');
    if(!profile?.id) throw new Error('Student profile could not be loaded. Please refresh once and try again.');
    const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';
    const path=`${profile.id}/profile-${Date.now()}.${ext}`;
    msg.textContent=' Uploading picture…';
    const up=await withTimeout(sb.storage.from('profile-media').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'3600'}),15000,'Profile picture upload');
    if(up.error) throw up.error;
    const url=sb.storage.from('profile-media').getPublicUrl(path).data.publicUrl + `?v=${Date.now()}`;
    const result=await withTimeout(sb.from('profiles').update({profile_picture_url:url}).eq('id',profile.id).select('*').maybeSingle(),15000,'Profile update');
    if(result.error) throw result.error;
    if(!result.data) throw new Error('Profile update did not return a record. Check profile permissions.');
    me=result.data;window.me=me;fillProfile();
    const input=el('profilePictureFile');if(input)input.value='';
    if(msg){msg.textContent=' ✓ Profile picture uploaded successfully.';msg.className='success';}
  } catch(e){
    console.error('Profile picture upload failed',e);
    if(msg){msg.textContent=` ${e?.message||e}`;msg.className='error';}
  }
}
function initProfilePicturePreview(){const input=el('profilePictureFile'),img=el('studentAvatar'),ph=el('studentAvatarPlaceholder'),msg=el('profilePicturePreviewMsg');if(!input||input.dataset.bound==='1')return;input.dataset.bound='1';input.addEventListener('change',()=>{const f=input.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return;if(img){img.src=URL.createObjectURL(f);img.classList.add('visible');}if(ph)ph.classList.add('hide');if(msg)msg.textContent='Preview ready. Click Upload picture to save it.';});}
function renderCV(){const skills=(me.skills||[]).map(esc).join(', ')||'Not provided';const certs=(me.certifications||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Not provided</li>';const projects=(me.projects||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Not provided</li>';el('cvPaper').innerHTML=`<h2>${esc(me.full_name||'Student')}</h2><div class="cv-contact">${esc(me.email||'')}${me.phone?' · '+esc(me.phone):''}${me.preferred_location?' · '+esc(me.preferred_location):''}</div><h4>Career Profile</h4><p>${esc(me.department||'Student')} · Roll No: ${esc(me.roll_no||'')} · CGPA: ${esc(me.cgpa??'')}</p><h4>Technical Skills</h4><p>${skills}</p><h4>Certifications</h4><ul>${certs}</ul><h4>Projects</h4><ul>${projects}</ul><h4>Internship / Experience</h4><p>${esc(me.experience||'Not provided')}</p><h4>Declaration</h4><p>I hereby declare that the information provided above is true and correct to the best of my knowledge.</p>`;}
function printCV(){renderCV();window.print();}
function clearCVPreview(){renderCV();}

async function extractCV(){
  const f=el('cvFile').files?.[0];if(!f){el('cvStatus').textContent='Choose a PDF or TXT file first.';return;}
  el('cvStatus').textContent='Extracting CV…';let text='';
  try{
    if(f.name.toLowerCase().endsWith('.txt')) text=await f.text();
    else {
      if(!window.pdfjsLib)throw new Error('PDF reader library did not load. Refresh the page and try again.');
      pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
      const doc=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;
      for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i);const c=await page.getTextContent();text+=c.items.map(x=>x.str).join(' ')+'\n';}
    }
    const {error}=await sb.from('profiles').update({resume_text:text,resume_name:f.name}).eq('id',me.id);if(error)throw error;
    me.resume_text=text;me.resume_name=f.name;el('cvStatus').textContent=`✓ Extracted ${text.length} characters from ${f.name}.`;await loadJobs();updateHome();
  }catch(e){el('cvStatus').textContent='CV extraction failed: '+(e.message||e);}
}
function tokens(s){return new Set((String(s||'').toLowerCase().match(/[a-z][a-z0-9+#.-]{1,}/g)||[]));}
function matchJob(j){const skills=(j.required_skills||[]).map(x=>String(x).toLowerCase());const cv=tokens([...(me.skills||[]),...(me.certifications||[]),...(me.projects||[]),me.resume_text||''].join(' '));const raw=String(me.resume_text||'').toLowerCase();const hit=skills.filter(x=>cv.has(x)||raw.includes(x));let score=skills.length?hit.length/skills.length*70:50;if(me.cgpa!=null&&j.min_cgpa!=null)score+=Number(me.cgpa)>=Number(j.min_cgpa)?20:0;else score+=10;if(j.location&&me.preferred_location&&j.location.toLowerCase().includes(me.preferred_location.toLowerCase()))score+=10;return {score:Math.min(100,Math.round(score)),missing:skills.filter(x=>!hit.includes(x))};}
async function loadJobs(){const {data,error}=await sb.from('jobs').select('*').eq('active',true).order('created_at',{ascending:false});if(error){el('jobList').innerHTML=`<div class="error">${esc(error.message)}</div>`;return}jobsData=data||[];renderJobs();}
function renderJobs(){const q=(el('jobSearch')?.value||'').toLowerCase();const list=jobsData.filter(j=>`${j.title} ${j.company} ${j.location} ${(j.required_skills||[]).join(' ')}`.toLowerCase().includes(q));el('jobList').innerHTML=list.map(j=>{const m=matchJob(j);const deadline=j.deadline?` · Deadline ${esc(j.deadline)}`:'';return `<div class="row" style="align-items:flex-start"><span><b>${esc(j.title)}</b><br><small>${esc(j.company||'')} · ${esc(j.location||'')} · Min CGPA ${j.min_cgpa??'—'}${deadline}</small><br><small>Skills: ${esc((j.required_skills||[]).join(', ')||'Not specified')}</small><br><small>Smart match: <b>${m.score}%</b>${m.missing.length?' · Missing: '+esc(m.missing.join(', ')):''}</small></span><span><button class="outline-btn" onclick="openJobCV('${j.id}')">Prepare CV</button> <button class="primary" onclick='applyJob(${JSON.stringify(j.id)},${m.score},${JSON.stringify(m.missing)})'>Apply</button></span></div>`}).join('')||'<div class="empty">No matching active jobs.</div>';}
async function applyJob(id,score,missing){const j=jobsData.find(x=>x.id===id);const required=typeof missingRequiredCVFields==='function'?missingRequiredCVFields(j,me):[];if(required.length){alert('Please complete the required CV fields first: '+required.map(x=>x.label).join(', ')+'. Open Prepare CV and save the required information.');return;}const {error}=await sb.from('applications').insert({job_id:id,student_id:me.id,status:'Applied',cv_text:me.resume_text||'',match_score:score,missing_skills:missing});if(error){alert(error.code==='23505'?'You have already applied for this job.':error.message);return}await sb.from('notifications').insert({student_id:me.id,title:'Application submitted',body:`Your application for ${j?.title||'the job'} has been submitted. Match score: ${score}%.`,type:'Application'});alert('Application submitted successfully.');await loadApps();updateHome();}
async function loadApps(){const {data,error}=await sb.from('applications').select('*,jobs(title,company,location,company_id)').eq('student_id',me.id).order('applied_at',{ascending:false});if(error){el('applicationSummary').textContent=error.message;return}apps=data||[];el('appCount').textContent=apps.length;el('applicationSummary').innerHTML=apps.length?apps.map(a=>`${esc(a.jobs?.title||'Job')}: <b>${esc(a.status)}</b> (${a.match_score||0}%)${a.status==='Selected'&&a.jobs?.company_id?` <button class="outline-btn" onclick="contactCompany('${a.jobs.company_id}')">Contact Company</button>`:''}`).join(' · '):'No applications yet.';}
async function loadInterviews(){const {data,error}=await sb.from('interviews').select('*,jobs(title,company)').eq('student_id',me.id).order('scheduled_at');if(error){el('interviewList').innerHTML=`<div class="error">${esc(error.message)}</div>`;return}interviews=data||[];el('interviewCount').textContent=interviews.filter(i=>new Date(i.scheduled_at)>=new Date()&&i.status!=='Completed').length;el('interviewList').innerHTML=interviews.map(i=>`<div class="row"><span><b>${esc(i.jobs?.title||'Interview')}</b> · ${esc(i.jobs?.company||'')}<br><small>${new Date(i.scheduled_at).toLocaleString()} · ${esc(i.mode)} · ${esc(i.status)}${i.location?' · '+esc(i.location):''}</small></span><span>${i.meeting_link?`<a class="outline-btn" target="_blank" rel="noopener" href="${esc(i.meeting_link)}">Join</a>`:''}</span></div>`).join('')||'<div class="empty">No interviews scheduled.</div>';}
async function loadNotifications(){const {data,error}=await sb.from('notifications').select('*').eq('student_id',me.id).order('created_at',{ascending:false});if(error){el('notificationList').innerHTML=`<div class="error">${esc(error.message)}</div>`;return}const list=data||[];el('notificationSummary').textContent=`${list.filter(n=>!n.read).length} unread notification(s).`;el('notificationList').innerHTML=list.map(n=>`<div class="row"><span><b>${esc(n.title)}</b><br><small>${esc(n.body)}</small></span><small>${new Date(n.created_at).toLocaleString()}${n.read?' · Read':''}</small></div>`).join('')||'<div class="empty">No notifications.</div>';}
async function markNotificationsRead(){const {error}=await sb.from('notifications').update({read:true}).eq('student_id',me.id).eq('read',false);if(error)alert(error.message);await loadNotifications();updateHome();}
async function loadPractice(){const cat=el('practiceFilter')?.value||'',year=el('practiceYear')?.value||'';let q=sb.from('practice_questions').select('*').order('created_at',{ascending:false});if(cat)q=q.eq('category',cat);if(year)q=q.eq('year',year);const {data,error}=await q;if(error)return el('practiceList').innerHTML=`<div class="error">${esc(error.message)}</div>`;el('practiceList').innerHTML=(data||[]).map((x,i)=>`<div class="row"><span><b>${i+1}. ${esc(x.question)}</b><br><small>${esc(x.category)} · ${esc(x.difficulty)} · ${esc(x.year||'')}</small><details><summary>Show answer</summary><p>${esc(x.answer||'')}</p></details></span></div>`).join('')||'<div class="empty">No questions found.</div>';}
async function loadHistory(){const {data,error}=await sb.from('placement_history').select('*').order('visit_date',{ascending:false});if(error)return el('historyList').innerHTML=`<div class="error">${esc(error.message)}</div>`;el('historyList').innerHTML=(data||[]).map(h=>`<div class="row"><span><b>${esc(h.company_name)}</b><br><small>${esc(h.department||'All departments')} · ${h.students_placed||0} placed · Avg ₹${h.average_package||0} · Highest ₹${h.highest_package||0}</small></span></div>`).join('')||'<div class="empty">No placement history published.</div>';}
async function loadPlacementStats(){const {data,error}=await sb.from('placement_stats').select('*').eq('id',1).single();if(error||!data)return;el('psTotal').textContent=data.total_students||0;el('psCompanies').textContent=data.companies||0;el('psPlaced').textContent=data.students_placed||0;el('psActive').textContent=data.active_drives||0;}
function updateHome(){el('jobCount').textContent=jobsData.length;el('matchCount').textContent=jobsData.filter(j=>matchJob(j).score>=60).length;el('recommendations').textContent=jobsData.length?jobsData.filter(j=>matchJob(j).score>=60).slice(0,4).map(j=>`${j.title} (${matchJob(j).score}%)`).join(' · '):'No recommendations yet.';}
async function contactTPO(){const subject=el('studentSubject').value.trim(),body=el('studentBody').value.trim();if(!subject||!body)return alert('Enter a subject and message.');const {data:tpos}=await sb.from('profiles').select('id').eq('role','tpo').eq('is_active',true).limit(1);if(!tpos?.length)return el('studentContactMsg').textContent='No active TPO account found.';const {error}=await sb.from('messages').insert({sender_id:me.id,receiver_id:tpos[0].id,subject,body});el('studentContactMsg').textContent=error?` ${error.message}`:' ✓ Message sent';el('studentContactMsg').className=error?'error':'success';if(!error){el('studentSubject').value='';el('studentBody').value='';}}
async function contactCompany(companyId){const subject=prompt('Subject for company');if(!subject)return;const body=prompt('Message');if(!body)return;const {error}=await sb.from('messages').insert({sender_id:me.id,company_id:companyId,subject,body});alert(error?error.message:'Message sent to company.');}

let selectedCVJob=null;
function openJobCV(jobId){selectedCVJob=jobsData.find(j=>j.id===jobId);if(!selectedCVJob)return;el('cvJobTitle').textContent=`CV for ${selectedCVJob.title}`;el('cvJobInfo').textContent=`${selectedCVJob.company||''} · ${selectedCVJob.location||'Location not specified'} · Format: ${selectedCVJob.cv_template_url?'Uploaded fillable PDF':(selectedCVJob.cv_template_type||'Web Professional')}`;el('cvJobStatus').textContent='Your current profile will be inserted automatically.';if(typeof renderStudentCVFields==='function')renderStudentCVFields('jobCVRequiredFields',selectedCVJob,me);el('cvJobBox').classList.remove('hide');el('cvJobBox').scrollIntoView({behavior:'smooth',block:'center'});}
function closeJobCV(){el('cvJobBox').classList.add('hide');selectedCVJob=null;}
function profileCVText(){return {name:me.full_name||'Student',email:me.email||'',phone:me.phone||'',dept:me.department||'',roll:me.roll_no||'',qualification:me.qualification||'',cgpa:me.cgpa??'',skills:me.skills||[],certs:me.certifications||[],projects:me.projects||[],location:me.preferred_location||'',experience:me.experience||'',extras:me.profile_extra_fields||{},picture:me.profile_picture_url||''};}
function cvFileName(job){return `${safeFile(me.full_name||'Student')}_${safeFile(job?.title||'CV')}.pdf`;}
function safeFile(s){return String(s||'').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'')||'Student';}
function wrapLines(text,font,size,maxWidth){const words=String(text??'').split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(font.widthOfTextAtSize(test,size)<=maxWidth)line=test;else{if(line)lines.push(line);line=word;}}if(line)lines.push(line);return lines;}
async function makeWebCV(job){
  const {PDFDocument,StandardFonts,rgb}=PDFLib;const pdf=await PDFDocument.create();let page=pdf.addPage([595,842]);const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const d=profileCVText();let cfg=null;try{cfg=job?.cv_template?JSON.parse(job.cv_template):null}catch{}const style=cfg?.style||String(job?.cv_template_type||'web-professional').replace('web-','');const accent=style==='modern'?rgb(.08,.35,.58):style==='minimal'?rgb(.15,.15,.15):rgb(.04,.12,.23);let y=790;const newPage=()=>{page=pdf.addPage([595,842]);y=790};const lineWrapped=(text,size=10,boldFont=false)=>{const lines=wrapLines(text||'Not provided',boldFont?bold:font,size,515);for(const l of lines){if(y<55)newPage();page.drawText(l,{x:40,y,size,font:boldFont?bold:font,color:rgb(.2,.3,.4)});y-=15;}y-=4;};const section=(title)=>{if(y<80)newPage();page.drawText(title.toUpperCase(),{x:40,y,size:10,font:bold,color:accent});page.drawLine({start:{x:40,y:y-4},end:{x:555,y:y-4},thickness:.6,color:rgb(.82,.86,.9)});y-=20;};page.drawText(d.name,{x:40,y,size:22,font:bold,color:accent});y-=20;lineWrapped([d.email,d.phone,d.location].filter(Boolean).join(' · '),9,false);y-=8;const sections=cfg?.sections||['profile','education','skills','certs','projects','experience','location','job'];for(const sec of sections){if(sec==='profile'){section('Profile');lineWrapped(`${d.dept||'Student'} · Roll No: ${d.roll||'—'} · CGPA: ${d.cgpa||'—'}`)}else if(sec==='education'){section('Education');lineWrapped(`${d.qualification||'Qualification not provided'} · ${d.dept||'Department / Branch'} · CGPA ${d.cgpa||'—'}`)}else if(sec==='skills'){section('Technical Skills');lineWrapped(d.skills.join(', '))}else if(sec==='certs'){section('Certifications');lineWrapped(d.certs.length?d.certs.join(' · '):'Not provided')}else if(sec==='projects'){section('Projects');lineWrapped(d.projects.length?d.projects.join(' · '):'Not provided')}else if(sec==='experience'){section('Internship / Experience');lineWrapped(d.experience)}else if(sec==='location'){section('Preferred Location');lineWrapped(d.location)}else if(sec==='job'){section('Job Details');lineWrapped(`${job?.title||''} · ${job?.company||''}`)}}const req=normalizeCVFields(job?.cv_required_fields);for(const f of req.filter(x=>x.key&&!sections.includes(x.key))){if(['full_name','email','phone','profile_picture','roll_no','department','qualification','cgpa','skills','certifications','projects','experience','preferred_location'].includes(f.key))continue;const value=findCVFieldValue(me,f.key);if(value){section(f.label);lineWrapped(String(value));}}return pdf.save();
}
async function makePdfTemplateCV(job){
  const res=await fetch(job.cv_template_url);if(!res.ok)throw new Error('Unable to load the uploaded PDF template.');const pdf=await PDFLib.PDFDocument.load(await res.arrayBuffer());const form=pdf.getForm();const fields=form.getFields();if(!fields.length)throw new Error('The uploaded PDF has no fillable fields.');const d=profileCVText();const map={full_name:d.name,name:d.name,student_name:d.name,email:d.email,phone:d.phone,roll_no:d.roll,roll_number:d.roll,rollno:d.roll,department:d.dept,branch:d.dept,qualification:d.qualification,cgpa:String(d.cgpa||''),skills:d.skills.join(', '),technical_skills:d.skills.join(', '),certifications:d.certs.join(', '),projects:d.projects.join('\n'),experience:d.experience,preferred_location:d.location,preferredlocation:d.location,location:d.location,job_title:job.title||'',jobtitle:job.title||'',company_name:job.company||'',companyname:job.company||'',required_skills:(job.required_skills||[]).join(', '),requiredskills:(job.required_skills||[]).join(', '),...Object.fromEntries(Object.entries(d.extras||{}).map(([k,v])=>[k,String(v??'')]))};const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'');let filled=0;for(const f of fields){const n=norm(f.getName());const key=Object.keys(map).find(k=>n===norm(k)||n.includes(norm(k))||norm(k).includes(n));if(key&&typeof f.setText==='function'){try{f.setText(String(map[key]??''));filled++;}catch{}}}if(!filled)throw new Error('No matching field names were found in this template. Use fields such as FULL_NAME, EMAIL, PHONE, DEPARTMENT, ROLL_NO, CGPA, SKILLS, PROJECTS and EXPERIENCE.');try{form.flatten();}catch{}return pdf.save();
}
async function saveJobCVFields(){
  if(!selectedCVJob)return;const msg=el('jobCVFieldMsg');msg.textContent='Saving…';const root=el('jobCVRequiredFields');if(!root)return;const extras={...(me.profile_extra_fields||{})};const patch={};const standardKeys=new Set(['full_name','email','phone','roll_no','department','qualification','cgpa','skills','certifications','projects','experience','preferred_location']);root.querySelectorAll('[data-extra-field]').forEach(input=>{const key=input.dataset.extraField;const value=input.value.trim();if(standardKeys.has(key)){if(key==='skills'||key==='certifications')patch[key]=value.split(',').map(x=>x.trim()).filter(Boolean);else if(key==='projects')patch[key]=value.split('\n').map(x=>x.trim()).filter(Boolean);else if(key==='cgpa')patch[key]=value?Number(value):null;else patch[key]=value;}else extras[key]=value;});patch.profile_extra_fields=extras;const {data,error}=await sb.from('profiles').update(patch).eq('id',me.id).select('*').single();if(error){msg.textContent=error.message;msg.className='error';return;}me=data;window.me=me;renderStudentCVFields('jobCVRequiredFields',selectedCVJob,me);const still=missingRequiredCVFields(selectedCVJob,me);msg.textContent=still.length?('Saved. Still required: '+still.map(x=>x.label).join(', ')):'✓ Required information saved';msg.className=still.length?'muted':'success';
}
async function downloadSelectedJobCV(){if(!selectedCVJob)return;const missing=missingRequiredCVFields(selectedCVJob,me);if(missing.length){alert('Complete these required CV fields first: '+missing.map(x=>x.label).join(', '));return;}const status=el('cvJobStatus');status.textContent='Preparing your job-specific CV…';try{const bytes=selectedCVJob.cv_template_url?await makePdfTemplateCV(selectedCVJob):await makeWebCV(selectedCVJob);const blob=new Blob([bytes],{type:'application/pdf'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=cvFileName(selectedCVJob);a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);status.textContent='✓ CV downloaded.';}catch(e){status.textContent='CV generation failed: '+(e.message||e);}}

guard();
